### ISSUE TITLE
how to add the search Box?

### ISSUE THREAD

**Issue by wenlai-lavine** [alexzhangs/alexzhangs.github.io#4]
Hi, thanks for the awesome search box in your blog. I'd like to add the search box also in my personal blog, could you please give a detail steps to tell us how to add the search box? Thank you very much!

**Comment by alexzhangs** [comment]
If you plan to use the same theme, the simplest way is to fork this repo and make the necessary change on your own.
Or the middle way, use this theme `remote_theme: alexforks/jekyll-theme-yat` rather than `remote_theme: jeffreytse/jekyll-theme-yat`, and refer to my [config](https://github.com/alexzhangs/alexzhangs.github.io/blob/main/_config.yml). 


If you are using another theme, then you will have to get your hands dirty.
Anyway you may want to look into this post: https://www.0xbeta.com/software/2021/10/17/Welcome-To-Alexs-Personal-Blog.html#h-search-box
